language: node_js
node_js:
  - "10"
# command to only run master branch
branches:
  only:
  - master
  
before_install:
  - npm i -g npm@6.8.0

# command to install dependencies
install:
  - cd client
  - npm install 
  - cd ../
  - npm install 
  
  
cache:
  directories:
    - "./node_modules"
    - "./client/node_modules"
services:
  - mongodb  
  
env:
  - NODE_ENV = "test"
  - NODE_ENV = "production"


#command to run tests
script:
  - npm test
# option for slack integration
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
