language: node_js
node_js:
  - "node"
  - "10"
# command to only run master branch
branches:
  only:
  - master
# command to install dependencies
install:
  - npm install
#command to run tests
script:
  - npm test
# option for slack integration
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt